sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 76993965996@Mysql
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: LTIAMSBBCV
    access-key-id: SK23sd34
    bucket-name: sky
